// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Educ.adk.Areas.Ecole.DataContext;

namespace School.Educ.adk.Migrations.EcoleDbMigrations
{
    [DbContext(typeof(EcoleDb))]
    [Migration("20210302082114_02_03_2021_2")]
    partial class _02_03_2021_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.CahierCote", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoursID")
                        .IsRequired();

                    b.Property<string>("Periode")
                        .IsRequired();

                    b.Property<double>("Total");

                    b.HasKey("ID");

                    b.HasIndex("CoursID")
                        .IsUnique();

                    b.ToTable("CahierCote");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Categorie", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom");

                    b.HasKey("ID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Classe", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnneeScolaire")
                        .IsRequired();

                    b.Property<string>("EcoleID");

                    b.Property<string>("Niveau")
                        .IsRequired();

                    b.Property<string>("Section")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("EcoleID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Cotation", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EleveID")
                        .IsRequired();

                    b.Property<string>("EpreuveID");

                    b.Property<double>("Point");

                    b.HasKey("ID");

                    b.HasIndex("EleveID");

                    b.HasIndex("EpreuveID");

                    b.ToTable("Cotations");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Cours", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categorie")
                        .IsRequired();

                    b.Property<string>("ClasseID");

                    b.Property<string>("Intituler")
                        .IsRequired();

                    b.Property<string>("ProfesseurID")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("ClasseID");

                    b.HasIndex("ProfesseurID");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Directeur", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateNaissance");

                    b.Property<string>("Email");

                    b.Property<int?>("Genre");

                    b.Property<string>("Matricule")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Postnom")
                        .IsRequired();

                    b.Property<string>("Prenom")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Directeurs");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Ecole", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreate");

                    b.Property<string>("DirecteurID");

                    b.Property<string>("EcoleLatitude")
                        .IsRequired();

                    b.Property<string>("EcoleLongitude")
                        .IsRequired();

                    b.Property<double>("Niveau");

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("SousDivision")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("DirecteurID")
                        .IsUnique()
                        .HasFilter("[DirecteurID] IS NOT NULL");

                    b.ToTable("Ecoles");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Eleve", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateNaissance");

                    b.Property<string>("EcoleID");

                    b.Property<int?>("Genre");

                    b.Property<string>("Matricule")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Postnom")
                        .IsRequired();

                    b.Property<string>("Prenom")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("EcoleID");

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Epreuve", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CahierCoteID");

                    b.Property<DateTime>("DateEpreuve");

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<double>("Total");

                    b.HasKey("ID");

                    b.HasIndex("CahierCoteID");

                    b.ToTable("Epreuve");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Inscription", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClasseID");

                    b.Property<DateTime>("DateInscription");

                    b.Property<string>("EleveId");

                    b.HasKey("ID");

                    b.HasIndex("ClasseID");

                    b.HasIndex("EleveId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Inspecteur", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateNaissance");

                    b.Property<string>("EcoleID");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int?>("Genre");

                    b.Property<string>("Matricule")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Postnom")
                        .IsRequired();

                    b.Property<string>("Prenom")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("EcoleID")
                        .IsUnique()
                        .HasFilter("[EcoleID] IS NOT NULL");

                    b.ToTable("Inspecteurs");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Lecon", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoursID")
                        .IsRequired();

                    b.Property<DateTime>("DateLecon");

                    b.Property<string>("LeconDonnee")
                        .IsRequired();

                    b.Property<string>("ProfesseurID");

                    b.HasKey("ID");

                    b.HasIndex("CoursID");

                    b.HasIndex("ProfesseurID");

                    b.ToTable("Lecons");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Option", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("SectionID");

                    b.HasKey("ID");

                    b.HasIndex("SectionID");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Professeur", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateNaissance");

                    b.Property<string>("EcoleID");

                    b.Property<string>("Email");

                    b.Property<int?>("Genre");

                    b.Property<string>("Matricule")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Postnom")
                        .IsRequired();

                    b.Property<string>("Prenom")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("EcoleID");

                    b.ToTable("Professeurs");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Section", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.SousDivision", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LocalDescript")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("SousDivisions");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Evaluer", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cotation");

                    b.Property<string>("InpecteurID");

                    b.Property<string>("LeconID");

                    b.Property<string>("Remarque");

                    b.HasKey("ID");

                    b.HasIndex("InpecteurID");

                    b.HasIndex("LeconID")
                        .IsUnique()
                        .HasFilter("[LeconID] IS NOT NULL");

                    b.ToTable("Evaluer");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.CahierCote", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Cours", "Cours")
                        .WithOne("CahierCote")
                        .HasForeignKey("School.Educ.adk.Areas.Ecole.Models.CahierCote", "CoursID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Classe", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Ecole", "Ecole")
                        .WithMany("Classes")
                        .HasForeignKey("EcoleID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Cotation", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("EleveID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Epreuve", "Epreuve")
                        .WithMany("Cotations")
                        .HasForeignKey("EpreuveID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Cours", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Classe", "Classe")
                        .WithMany("Cours")
                        .HasForeignKey("ClasseID");

                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Professeur", "Professeur")
                        .WithMany("Cours")
                        .HasForeignKey("ProfesseurID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Ecole", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Directeur", "Directeur")
                        .WithOne("Ecole")
                        .HasForeignKey("School.Educ.adk.Areas.Ecole.Models.Ecole", "DirecteurID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Eleve", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Ecole", "Ecole")
                        .WithMany("Eleves")
                        .HasForeignKey("EcoleID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Epreuve", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.CahierCote", "CahierCote")
                        .WithMany("Epreuves")
                        .HasForeignKey("CahierCoteID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Inscription", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Classe", "Classe")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ClasseID");

                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Eleve", "Eleve")
                        .WithMany("Inscriptions")
                        .HasForeignKey("EleveId");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Inspecteur", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Ecole", "Ecole")
                        .WithOne("Inspecteur")
                        .HasForeignKey("School.Educ.adk.Areas.Ecole.Models.Inspecteur", "EcoleID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Lecon", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("CoursID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Professeur", "Professeur")
                        .WithMany()
                        .HasForeignKey("ProfesseurID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Option", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Section", "Section")
                        .WithMany("Options")
                        .HasForeignKey("SectionID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Ecole.Models.Professeur", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Ecole", "Ecole")
                        .WithMany("Professeurs")
                        .HasForeignKey("EcoleID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Evaluer", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Inspecteur", "Inpecteur")
                        .WithMany()
                        .HasForeignKey("InpecteurID");

                    b.HasOne("School.Educ.adk.Areas.Ecole.Models.Lecon", "Lecon")
                        .WithOne("Evaluer")
                        .HasForeignKey("School.Educ.adk.Areas.Inspection.Models.Evaluer", "LeconID");
                });
#pragma warning restore 612, 618
        }
    }
}
