// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Educ.adk.Areas.Inspection.Data;

namespace School.Educ.adk.Migrations.ExamenDbMigrations
{
    [DbContext(typeof(ExamenDb))]
    [Migration("20201112125040__init_Exmanedb")]
    partial class _init_Exmanedb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Assertion", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Intituler")
                        .IsRequired();

                    b.Property<string>("QuestionID")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Assertions");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Examen", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeAcces")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<string>("IdInspecteur")
                        .IsRequired();

                    b.Property<string>("Periode")
                        .IsRequired();

                    b.Property<string>("Serie")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Examens");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Participant", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateExamen");

                    b.Property<string>("IdentifiantEleve")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Question", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BonneReponse");

                    b.Property<double>("Cote");

                    b.Property<string>("Enoncer");

                    b.Property<string>("ExamenID");

                    b.HasKey("ID");

                    b.HasIndex("ExamenID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Reponse", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ParticipantID");

                    b.Property<double>("Point");

                    b.Property<string>("QuestionID");

                    b.Property<string>("ReponseDonnee")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("ParticipantID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Reponses");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Assertion", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Inspection.Models.Question", "Question")
                        .WithMany("Assertion")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Question", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Inspection.Models.Examen", "Examen")
                        .WithMany("Questions")
                        .HasForeignKey("ExamenID");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Inspection.Models.Reponse", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Inspection.Models.Participant", "Participant")
                        .WithMany("Reponses")
                        .HasForeignKey("ParticipantID");

                    b.HasOne("School.Educ.adk.Areas.Inspection.Models.Question", "Question")
                        .WithMany("Reponse")
                        .HasForeignKey("QuestionID");
                });
#pragma warning restore 612, 618
        }
    }
}
