// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Educ.adk.Areas.Inspection.Data;

namespace School.Educ.adk.Migrations.ExamenDbMigrations
{
    [DbContext(typeof(ExamenDb))]
    [Migration("20210112113021__12_01_2021_2")]
    partial class _12_01_2021_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("School.Educ.adk.Areas.Professeur.Models.Echange", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cotation");

                    b.Property<string>("Inspecteur");

                    b.Property<string>("LeconID");

                    b.Property<string>("Remarque");

                    b.HasKey("ID");

                    b.HasIndex("LeconID")
                        .IsUnique()
                        .HasFilter("[LeconID] IS NOT NULL");

                    b.ToTable("Echange");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Professeur.Models.Lecon", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateLecon");

                    b.Property<string>("IdentifiantCours");

                    b.Property<string>("IdentifiantProfesseur");

                    b.Property<string>("LeconDonnee");

                    b.HasKey("ID");

                    b.ToTable("Lecon");
                });

            modelBuilder.Entity("School.Educ.adk.Areas.Professeur.Models.Echange", b =>
                {
                    b.HasOne("School.Educ.adk.Areas.Professeur.Models.Lecon", "Lecon")
                        .WithOne("Echange")
                        .HasForeignKey("School.Educ.adk.Areas.Professeur.Models.Echange", "LeconID");
                });
#pragma warning restore 612, 618
        }
    }
}
